import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-ev-charging-roaming-settlement-reconciliation",
  "engine": "recovery",
  "title": "EV Charging Roaming Settlement Reconciliation",
  "shortTitle": "EV Charging Roaming Settlement Reconciliation",
  "tagline": "Quantify, recover, and prevent financial leakage through ev charging roaming settlement reconciliation",
  "industry": "EV Charging Network Finance",
  "uiPort": 4626,
  "apiPort": 5626,
  "accent": "#b45309",
  "currency": "USD",
  "primaryOutcome": "EV Charging Roaming Settlement Reconciliation converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect roaming agreements, stations, EVSEs, connectors, charging sessions, metered energy, tariffs, session fees, markups, taxes, failures, refunds, partner statements, and cash in one accountable recovery workflow.",
  "calculation": {
    "actualKey": "receivedSettlement",
    "expectedKey": "expectedSettlement",
    "actualLabel": "Received Roaming Settlement",
    "expectedLabel": "Calculated Session Settlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "EV Charging Roaming Settlement Reconciliation evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective governing agreement and applicable rules",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare and submit the recovery or correction package",
      "Track counterparty response and reconcile realized outcome"
    ]
  }
},[
feature("partner-roaming-agreement-library","ECR01","Partner roaming agreement library","Execute partner roaming agreement library using roaming agreements, stations, EVSEs, connectors, charging sessions, metered energy, tariffs, session fees, markups, taxes, failures, refunds, partner statements, and cash.","Produce a governed partner roaming agreement library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Roaming Partner / Charging Network","text","Roaming Partner / Charging Network · Standard Case"],["caseReference","Partner roaming agreement library Reference","text","ECR01-2026-001"],["receivedSettlement","Received Roaming Settlement","currency",1067500],["expectedSettlement","Calculated Session Settlement","currency",1259650],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedSettlement",subjects:["Partner roaming agreement library case","Station EVSE registry case","Charging-session ingestion case","Metered energy validation case","Tariff time-of-use calculation case"]}),
feature("station-evse-registry","ECR02","Station EVSE registry","Execute station evse registry using roaming agreements, stations, EVSEs, connectors, charging sessions, metered energy, tariffs, session fees, markups, taxes, failures, refunds, partner statements, and cash.","Produce a governed station evse registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Roaming Partner / Charging Network","text","Roaming Partner / Charging Network · Standard Case"],["caseReference","Station EVSE registry Reference","text","ECR02-2026-001"],["receivedSettlement","Received Roaming Settlement","currency",1067500],["expectedSettlement","Calculated Session Settlement","currency",1259650],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedSettlement",subjects:["Partner roaming agreement library case","Station EVSE registry case","Charging-session ingestion case","Metered energy validation case","Tariff time-of-use calculation case"]}),
feature("charging-session-ingestion","ECR03","Charging-session ingestion","Execute charging-session ingestion using roaming agreements, stations, EVSEs, connectors, charging sessions, metered energy, tariffs, session fees, markups, taxes, failures, refunds, partner statements, and cash.","Produce a governed charging-session ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Roaming Partner / Charging Network","text","Roaming Partner / Charging Network · Standard Case"],["caseReference","Charging-session ingestion Reference","text","ECR03-2026-001"],["receivedSettlement","Received Roaming Settlement","currency",1067500],["expectedSettlement","Calculated Session Settlement","currency",1259650],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedSettlement",subjects:["Partner roaming agreement library case","Station EVSE registry case","Charging-session ingestion case","Metered energy validation case","Tariff time-of-use calculation case"]}),
feature("metered-energy-validation","ECR04","Metered energy validation","Execute metered energy validation using roaming agreements, stations, EVSEs, connectors, charging sessions, metered energy, tariffs, session fees, markups, taxes, failures, refunds, partner statements, and cash.","Produce a governed metered energy validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Roaming Partner / Charging Network","text","Roaming Partner / Charging Network · Standard Case"],["caseReference","Metered energy validation Reference","text","ECR04-2026-001"],["receivedSettlement","Received Roaming Settlement","currency",1067500],["expectedSettlement","Calculated Session Settlement","currency",1259650],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedSettlement",subjects:["Partner roaming agreement library case","Station EVSE registry case","Charging-session ingestion case","Metered energy validation case","Tariff time-of-use calculation case"]}),
feature("tariff-time-of-use-calculation","ECR05","Tariff time-of-use calculation","Execute tariff time-of-use calculation using roaming agreements, stations, EVSEs, connectors, charging sessions, metered energy, tariffs, session fees, markups, taxes, failures, refunds, partner statements, and cash.","Produce a governed tariff time-of-use calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Roaming Partner / Charging Network","text","Roaming Partner / Charging Network · Standard Case"],["caseReference","Tariff time-of-use calculation Reference","text","ECR05-2026-001"],["receivedSettlement","Received Roaming Settlement","currency",1067500],["expectedSettlement","Calculated Session Settlement","currency",1259650],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedSettlement",subjects:["Partner roaming agreement library case","Station EVSE registry case","Charging-session ingestion case","Metered energy validation case","Tariff time-of-use calculation case"]}),
feature("session-fee-calculation","ECR06","Session fee calculation","Execute session fee calculation using roaming agreements, stations, EVSEs, connectors, charging sessions, metered energy, tariffs, session fees, markups, taxes, failures, refunds, partner statements, and cash.","Produce a governed session fee calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Roaming Partner / Charging Network","text","Roaming Partner / Charging Network · Standard Case"],["caseReference","Session fee calculation Reference","text","ECR06-2026-001"],["receivedSettlement","Received Roaming Settlement","currency",1067500],["expectedSettlement","Calculated Session Settlement","currency",1259650],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedSettlement",subjects:["Partner roaming agreement library case","Station EVSE registry case","Charging-session ingestion case","Metered energy validation case","Tariff time-of-use calculation case"]}),
feature("roaming-markup-audit","ECR07","Roaming markup audit","Execute roaming markup audit using roaming agreements, stations, EVSEs, connectors, charging sessions, metered energy, tariffs, session fees, markups, taxes, failures, refunds, partner statements, and cash.","Produce a governed roaming markup audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Roaming Partner / Charging Network","text","Roaming Partner / Charging Network · Standard Case"],["caseReference","Roaming markup audit Reference","text","ECR07-2026-001"],["receivedSettlement","Received Roaming Settlement","currency",1067500],["expectedSettlement","Calculated Session Settlement","currency",1259650],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedSettlement",subjects:["Partner roaming agreement library case","Station EVSE registry case","Charging-session ingestion case","Metered energy validation case","Tariff time-of-use calculation case"]}),
feature("tax-currency-treatment","ECR08","Tax currency treatment","Execute tax currency treatment using roaming agreements, stations, EVSEs, connectors, charging sessions, metered energy, tariffs, session fees, markups, taxes, failures, refunds, partner statements, and cash.","Produce a governed tax currency treatment decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Roaming Partner / Charging Network","text","Roaming Partner / Charging Network · Standard Case"],["caseReference","Tax currency treatment Reference","text","ECR08-2026-001"],["receivedSettlement","Received Roaming Settlement","currency",1067500],["expectedSettlement","Calculated Session Settlement","currency",1259650],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedSettlement",subjects:["Partner roaming agreement library case","Station EVSE registry case","Charging-session ingestion case","Metered energy validation case","Tariff time-of-use calculation case"]}),
feature("failed-partial-session-control","ECR09","Failed partial session control","Execute failed partial session control using roaming agreements, stations, EVSEs, connectors, charging sessions, metered energy, tariffs, session fees, markups, taxes, failures, refunds, partner statements, and cash.","Produce a governed failed partial session control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Roaming Partner / Charging Network","text","Roaming Partner / Charging Network · Standard Case"],["caseReference","Failed partial session control Reference","text","ECR09-2026-001"],["receivedSettlement","Received Roaming Settlement","currency",1067500],["expectedSettlement","Calculated Session Settlement","currency",1259650],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedSettlement",subjects:["Partner roaming agreement library case","Station EVSE registry case","Charging-session ingestion case","Metered energy validation case","Tariff time-of-use calculation case"]}),
feature("refund-adjustment-control","ECR10","Refund adjustment control","Execute refund adjustment control using roaming agreements, stations, EVSEs, connectors, charging sessions, metered energy, tariffs, session fees, markups, taxes, failures, refunds, partner statements, and cash.","Produce a governed refund adjustment control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Roaming Partner / Charging Network","text","Roaming Partner / Charging Network · Standard Case"],["caseReference","Refund adjustment control Reference","text","ECR10-2026-001"],["receivedSettlement","Received Roaming Settlement","currency",1067500],["expectedSettlement","Calculated Session Settlement","currency",1259650],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedSettlement",subjects:["Partner roaming agreement library case","Station EVSE registry case","Charging-session ingestion case","Metered energy validation case","Tariff time-of-use calculation case"]}),
feature("partner-settlement-reconciliation","ECR11","Partner settlement reconciliation","Execute partner settlement reconciliation using roaming agreements, stations, EVSEs, connectors, charging sessions, metered energy, tariffs, session fees, markups, taxes, failures, refunds, partner statements, and cash.","Produce a governed partner settlement reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Roaming Partner / Charging Network","text","Roaming Partner / Charging Network · Standard Case"],["caseReference","Partner settlement reconciliation Reference","text","ECR11-2026-001"],["receivedSettlement","Received Roaming Settlement","currency",1067500],["expectedSettlement","Calculated Session Settlement","currency",1259650],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedSettlement",subjects:["Partner roaming agreement library case","Station EVSE registry case","Charging-session ingestion case","Metered energy validation case","Tariff time-of-use calculation case"]}),
feature("network-fee-audit","ECR12","Network fee audit","Execute network fee audit using roaming agreements, stations, EVSEs, connectors, charging sessions, metered energy, tariffs, session fees, markups, taxes, failures, refunds, partner statements, and cash.","Produce a governed network fee audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Roaming Partner / Charging Network","text","Roaming Partner / Charging Network · Standard Case"],["caseReference","Network fee audit Reference","text","ECR12-2026-001"],["receivedSettlement","Received Roaming Settlement","currency",1067500],["expectedSettlement","Calculated Session Settlement","currency",1259650],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedSettlement",subjects:["Partner roaming agreement library case","Station EVSE registry case","Charging-session ingestion case","Metered energy validation case","Tariff time-of-use calculation case"]}),
feature("dispute-workflow","ECR13","Dispute workflow","Execute dispute workflow using roaming agreements, stations, EVSEs, connectors, charging sessions, metered energy, tariffs, session fees, markups, taxes, failures, refunds, partner statements, and cash.","Produce a governed dispute workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Roaming Partner / Charging Network","text","Roaming Partner / Charging Network · Standard Case"],["caseReference","Dispute workflow Reference","text","ECR13-2026-001"],["receivedSettlement","Received Roaming Settlement","currency",1067500],["expectedSettlement","Calculated Session Settlement","currency",1259650],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedSettlement",subjects:["Partner roaming agreement library case","Station EVSE registry case","Charging-session ingestion case","Metered energy validation case","Tariff time-of-use calculation case"]}),
feature("cash-reconciliation","ECR14","Cash reconciliation","Execute cash reconciliation using roaming agreements, stations, EVSEs, connectors, charging sessions, metered energy, tariffs, session fees, markups, taxes, failures, refunds, partner statements, and cash.","Produce a governed cash reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Roaming Partner / Charging Network","text","Roaming Partner / Charging Network · Standard Case"],["caseReference","Cash reconciliation Reference","text","ECR14-2026-001"],["receivedSettlement","Received Roaming Settlement","currency",1067500],["expectedSettlement","Calculated Session Settlement","currency",1259650],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedSettlement",subjects:["Partner roaming agreement library case","Station EVSE registry case","Charging-session ingestion case","Metered energy validation case","Tariff time-of-use calculation case"]}),
feature("station-partner-economics","ECR15","Station partner economics","Execute station partner economics using roaming agreements, stations, EVSEs, connectors, charging sessions, metered energy, tariffs, session fees, markups, taxes, failures, refunds, partner statements, and cash.","Produce a governed station partner economics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Roaming Partner / Charging Network","text","Roaming Partner / Charging Network · Standard Case"],["caseReference","Station partner economics Reference","text","ECR15-2026-001"],["receivedSettlement","Received Roaming Settlement","currency",1067500],["expectedSettlement","Calculated Session Settlement","currency",1259650],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedSettlement",subjects:["Partner roaming agreement library case","Station EVSE registry case","Charging-session ingestion case","Metered energy validation case","Tariff time-of-use calculation case"]})
]);
